/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as storeStoreLayoutRouteImport } from './routes/(store)/_store-layout'
import { Route as adminAuthLayoutRouteImport } from './routes/(admin)/_auth-layout'
import { Route as adminAdminLayoutRouteImport } from './routes/(admin)/_admin-layout'
import { Route as storeStoreLayoutIndexRouteImport } from './routes/(store)/_store-layout/index'
import { Route as storeStoreLayoutRegisterIndexRouteImport } from './routes/(store)/_store-layout/register/index'
import { Route as storeStoreLayoutLoginIndexRouteImport } from './routes/(store)/_store-layout/login/index'
import { Route as storeStoreLayoutCartIndexRouteImport } from './routes/(store)/_store-layout/cart/index'
import { Route as adminAuthLayoutAdminIndexRouteImport } from './routes/(admin)/_auth-layout/admin/index'
import { Route as storeStoreLayoutProductProductIdIndexRouteImport } from './routes/(store)/_store-layout/product/$productId/index'
import { Route as adminAuthLayoutAdminLoginIndexRouteImport } from './routes/(admin)/_auth-layout/admin/login/index'
import { Route as adminAdminLayoutAdminProductsIndexRouteImport } from './routes/(admin)/_admin-layout/admin/products/index'
import { Route as adminAdminLayoutAdminOrdersIndexRouteImport } from './routes/(admin)/_admin-layout/admin/orders/index'
import { Route as adminAdminLayoutAdminCustomersIndexRouteImport } from './routes/(admin)/_admin-layout/admin/customers/index'

const storeStoreLayoutRoute = storeStoreLayoutRouteImport.update({
  id: '/(store)/_store-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAuthLayoutRoute = adminAuthLayoutRouteImport.update({
  id: '/(admin)/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAdminLayoutRoute = adminAdminLayoutRouteImport.update({
  id: '/(admin)/_admin-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const storeStoreLayoutIndexRoute = storeStoreLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => storeStoreLayoutRoute,
} as any)
const storeStoreLayoutRegisterIndexRoute =
  storeStoreLayoutRegisterIndexRouteImport.update({
    id: '/register/',
    path: '/register/',
    getParentRoute: () => storeStoreLayoutRoute,
  } as any)
const storeStoreLayoutLoginIndexRoute =
  storeStoreLayoutLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => storeStoreLayoutRoute,
  } as any)
const storeStoreLayoutCartIndexRoute =
  storeStoreLayoutCartIndexRouteImport.update({
    id: '/cart/',
    path: '/cart/',
    getParentRoute: () => storeStoreLayoutRoute,
  } as any)
const adminAuthLayoutAdminIndexRoute =
  adminAuthLayoutAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => adminAuthLayoutRoute,
  } as any)
const storeStoreLayoutProductProductIdIndexRoute =
  storeStoreLayoutProductProductIdIndexRouteImport.update({
    id: '/product/$productId/',
    path: '/product/$productId/',
    getParentRoute: () => storeStoreLayoutRoute,
  } as any)
const adminAuthLayoutAdminLoginIndexRoute =
  adminAuthLayoutAdminLoginIndexRouteImport.update({
    id: '/admin/login/',
    path: '/admin/login/',
    getParentRoute: () => adminAuthLayoutRoute,
  } as any)
const adminAdminLayoutAdminProductsIndexRoute =
  adminAdminLayoutAdminProductsIndexRouteImport.update({
    id: '/admin/products/',
    path: '/admin/products/',
    getParentRoute: () => adminAdminLayoutRoute,
  } as any)
const adminAdminLayoutAdminOrdersIndexRoute =
  adminAdminLayoutAdminOrdersIndexRouteImport.update({
    id: '/admin/orders/',
    path: '/admin/orders/',
    getParentRoute: () => adminAdminLayoutRoute,
  } as any)
const adminAdminLayoutAdminCustomersIndexRoute =
  adminAdminLayoutAdminCustomersIndexRouteImport.update({
    id: '/admin/customers/',
    path: '/admin/customers/',
    getParentRoute: () => adminAdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof storeStoreLayoutIndexRoute
  '/admin/': typeof adminAuthLayoutAdminIndexRoute
  '/cart/': typeof storeStoreLayoutCartIndexRoute
  '/login/': typeof storeStoreLayoutLoginIndexRoute
  '/register/': typeof storeStoreLayoutRegisterIndexRoute
  '/admin/customers/': typeof adminAdminLayoutAdminCustomersIndexRoute
  '/admin/orders/': typeof adminAdminLayoutAdminOrdersIndexRoute
  '/admin/products/': typeof adminAdminLayoutAdminProductsIndexRoute
  '/admin/login/': typeof adminAuthLayoutAdminLoginIndexRoute
  '/product/$productId/': typeof storeStoreLayoutProductProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof storeStoreLayoutIndexRoute
  '/admin': typeof adminAuthLayoutAdminIndexRoute
  '/cart': typeof storeStoreLayoutCartIndexRoute
  '/login': typeof storeStoreLayoutLoginIndexRoute
  '/register': typeof storeStoreLayoutRegisterIndexRoute
  '/admin/customers': typeof adminAdminLayoutAdminCustomersIndexRoute
  '/admin/orders': typeof adminAdminLayoutAdminOrdersIndexRoute
  '/admin/products': typeof adminAdminLayoutAdminProductsIndexRoute
  '/admin/login': typeof adminAuthLayoutAdminLoginIndexRoute
  '/product/$productId': typeof storeStoreLayoutProductProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)/_admin-layout': typeof adminAdminLayoutRouteWithChildren
  '/(admin)/_auth-layout': typeof adminAuthLayoutRouteWithChildren
  '/(store)/_store-layout': typeof storeStoreLayoutRouteWithChildren
  '/(store)/_store-layout/': typeof storeStoreLayoutIndexRoute
  '/(admin)/_auth-layout/admin/': typeof adminAuthLayoutAdminIndexRoute
  '/(store)/_store-layout/cart/': typeof storeStoreLayoutCartIndexRoute
  '/(store)/_store-layout/login/': typeof storeStoreLayoutLoginIndexRoute
  '/(store)/_store-layout/register/': typeof storeStoreLayoutRegisterIndexRoute
  '/(admin)/_admin-layout/admin/customers/': typeof adminAdminLayoutAdminCustomersIndexRoute
  '/(admin)/_admin-layout/admin/orders/': typeof adminAdminLayoutAdminOrdersIndexRoute
  '/(admin)/_admin-layout/admin/products/': typeof adminAdminLayoutAdminProductsIndexRoute
  '/(admin)/_auth-layout/admin/login/': typeof adminAuthLayoutAdminLoginIndexRoute
  '/(store)/_store-layout/product/$productId/': typeof storeStoreLayoutProductProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/'
    | '/cart/'
    | '/login/'
    | '/register/'
    | '/admin/customers/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/login/'
    | '/product/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/login'
    | '/register'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/login'
    | '/product/$productId'
  id:
    | '__root__'
    | '/(admin)/_admin-layout'
    | '/(admin)/_auth-layout'
    | '/(store)/_store-layout'
    | '/(store)/_store-layout/'
    | '/(admin)/_auth-layout/admin/'
    | '/(store)/_store-layout/cart/'
    | '/(store)/_store-layout/login/'
    | '/(store)/_store-layout/register/'
    | '/(admin)/_admin-layout/admin/customers/'
    | '/(admin)/_admin-layout/admin/orders/'
    | '/(admin)/_admin-layout/admin/products/'
    | '/(admin)/_auth-layout/admin/login/'
    | '/(store)/_store-layout/product/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminAdminLayoutRoute: typeof adminAdminLayoutRouteWithChildren
  adminAuthLayoutRoute: typeof adminAuthLayoutRouteWithChildren
  storeStoreLayoutRoute: typeof storeStoreLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(store)/_store-layout': {
      id: '/(store)/_store-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof storeStoreLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_auth-layout': {
      id: '/(admin)/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/_admin-layout': {
      id: '/(admin)/_admin-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminAdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/_store-layout/': {
      id: '/(store)/_store-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof storeStoreLayoutIndexRouteImport
      parentRoute: typeof storeStoreLayoutRoute
    }
    '/(store)/_store-layout/register/': {
      id: '/(store)/_store-layout/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof storeStoreLayoutRegisterIndexRouteImport
      parentRoute: typeof storeStoreLayoutRoute
    }
    '/(store)/_store-layout/login/': {
      id: '/(store)/_store-layout/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof storeStoreLayoutLoginIndexRouteImport
      parentRoute: typeof storeStoreLayoutRoute
    }
    '/(store)/_store-layout/cart/': {
      id: '/(store)/_store-layout/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof storeStoreLayoutCartIndexRouteImport
      parentRoute: typeof storeStoreLayoutRoute
    }
    '/(admin)/_auth-layout/admin/': {
      id: '/(admin)/_auth-layout/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminAuthLayoutAdminIndexRouteImport
      parentRoute: typeof adminAuthLayoutRoute
    }
    '/(store)/_store-layout/product/$productId/': {
      id: '/(store)/_store-layout/product/$productId/'
      path: '/product/$productId'
      fullPath: '/product/$productId/'
      preLoaderRoute: typeof storeStoreLayoutProductProductIdIndexRouteImport
      parentRoute: typeof storeStoreLayoutRoute
    }
    '/(admin)/_auth-layout/admin/login/': {
      id: '/(admin)/_auth-layout/admin/login/'
      path: '/admin/login'
      fullPath: '/admin/login/'
      preLoaderRoute: typeof adminAuthLayoutAdminLoginIndexRouteImport
      parentRoute: typeof adminAuthLayoutRoute
    }
    '/(admin)/_admin-layout/admin/products/': {
      id: '/(admin)/_admin-layout/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof adminAdminLayoutAdminProductsIndexRouteImport
      parentRoute: typeof adminAdminLayoutRoute
    }
    '/(admin)/_admin-layout/admin/orders/': {
      id: '/(admin)/_admin-layout/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof adminAdminLayoutAdminOrdersIndexRouteImport
      parentRoute: typeof adminAdminLayoutRoute
    }
    '/(admin)/_admin-layout/admin/customers/': {
      id: '/(admin)/_admin-layout/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof adminAdminLayoutAdminCustomersIndexRouteImport
      parentRoute: typeof adminAdminLayoutRoute
    }
  }
}

interface adminAdminLayoutRouteChildren {
  adminAdminLayoutAdminCustomersIndexRoute: typeof adminAdminLayoutAdminCustomersIndexRoute
  adminAdminLayoutAdminOrdersIndexRoute: typeof adminAdminLayoutAdminOrdersIndexRoute
  adminAdminLayoutAdminProductsIndexRoute: typeof adminAdminLayoutAdminProductsIndexRoute
}

const adminAdminLayoutRouteChildren: adminAdminLayoutRouteChildren = {
  adminAdminLayoutAdminCustomersIndexRoute:
    adminAdminLayoutAdminCustomersIndexRoute,
  adminAdminLayoutAdminOrdersIndexRoute: adminAdminLayoutAdminOrdersIndexRoute,
  adminAdminLayoutAdminProductsIndexRoute:
    adminAdminLayoutAdminProductsIndexRoute,
}

const adminAdminLayoutRouteWithChildren =
  adminAdminLayoutRoute._addFileChildren(adminAdminLayoutRouteChildren)

interface adminAuthLayoutRouteChildren {
  adminAuthLayoutAdminIndexRoute: typeof adminAuthLayoutAdminIndexRoute
  adminAuthLayoutAdminLoginIndexRoute: typeof adminAuthLayoutAdminLoginIndexRoute
}

const adminAuthLayoutRouteChildren: adminAuthLayoutRouteChildren = {
  adminAuthLayoutAdminIndexRoute: adminAuthLayoutAdminIndexRoute,
  adminAuthLayoutAdminLoginIndexRoute: adminAuthLayoutAdminLoginIndexRoute,
}

const adminAuthLayoutRouteWithChildren = adminAuthLayoutRoute._addFileChildren(
  adminAuthLayoutRouteChildren,
)

interface storeStoreLayoutRouteChildren {
  storeStoreLayoutIndexRoute: typeof storeStoreLayoutIndexRoute
  storeStoreLayoutCartIndexRoute: typeof storeStoreLayoutCartIndexRoute
  storeStoreLayoutLoginIndexRoute: typeof storeStoreLayoutLoginIndexRoute
  storeStoreLayoutRegisterIndexRoute: typeof storeStoreLayoutRegisterIndexRoute
  storeStoreLayoutProductProductIdIndexRoute: typeof storeStoreLayoutProductProductIdIndexRoute
}

const storeStoreLayoutRouteChildren: storeStoreLayoutRouteChildren = {
  storeStoreLayoutIndexRoute: storeStoreLayoutIndexRoute,
  storeStoreLayoutCartIndexRoute: storeStoreLayoutCartIndexRoute,
  storeStoreLayoutLoginIndexRoute: storeStoreLayoutLoginIndexRoute,
  storeStoreLayoutRegisterIndexRoute: storeStoreLayoutRegisterIndexRoute,
  storeStoreLayoutProductProductIdIndexRoute:
    storeStoreLayoutProductProductIdIndexRoute,
}

const storeStoreLayoutRouteWithChildren =
  storeStoreLayoutRoute._addFileChildren(storeStoreLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  adminAdminLayoutRoute: adminAdminLayoutRouteWithChildren,
  adminAuthLayoutRoute: adminAuthLayoutRouteWithChildren,
  storeStoreLayoutRoute: storeStoreLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
